'use client'
import { useEffect, useMemo, useState } from 'react'
import Shell from '@/components/Shell'
import { createClient } from '@/lib/supabase'

type Startup={id:string;owner_id:string;name:string;sector:string|null;stage:string|null;description:string|null;country:string|null;funding_need_eur:number|null;verified:boolean}
type Investor={sectors:string[];stages:string[];geographies:string[];min_ticket_eur:number|null;max_ticket_eur:number|null;thesis:string|null}
type Match={startup:Startup;score:number;reasons:string[];gaps:string[]}
function computeMatch(s:Startup,i:Investor):Match{
  let score=0;const reasons:string[]=[];const gaps:string[]=[]
  if(i.sectors.length===0){score+=20;reasons.push('Secteur non contraint')}else if(s.sector&&i.sectors.some(x=>x.toLowerCase()===s.sector!.toLowerCase())){score+=25;reasons.push('Secteur compatible')}else gaps.push('Secteur hors mandat')
  if(i.stages.length===0){score+=15;reasons.push('Stade non contraint')}else if(s.stage&&i.stages.some(x=>x.toLowerCase()===s.stage!.toLowerCase())){score+=20;reasons.push('Stade compatible')}else gaps.push('Stade hors mandat')
  if(i.geographies.length===0){score+=10;reasons.push('Géographie non contrainte')}else if(s.country&&i.geographies.some(x=>x.toLowerCase()===s.country!.toLowerCase())){score+=15;reasons.push('Géographie compatible')}else gaps.push('Géographie hors mandat')
  if(s.funding_need_eur==null){score+=5;gaps.push('Besoin financier non renseigné')}else {const min=i.min_ticket_eur??0;const max=i.max_ticket_eur??Number.MAX_SAFE_INTEGER;if(s.funding_need_eur>=min&&s.funding_need_eur<=max){score+=25;reasons.push('Ticket compatible')}else if(s.funding_need_eur<=max*1.5&&s.funding_need_eur>=min*0.5){score+=10;gaps.push('Ticket proche du mandat')}else gaps.push('Ticket hors mandat')}
  if(s.verified){score+=10;reasons.push('Profil vérifié')}else gaps.push('Profil non vérifié')
  return {startup:s,score:Math.min(100,score),reasons,gaps}
}
export default function Matching(){
  const [investor,setInvestor]=useState<Investor|null>(null);const [startups,setStartups]=useState<Startup[]>([]);const [watch,setWatch]=useState<Set<string>>(new Set());const [message,setMessage]=useState('Chargement…')
  async function load(){const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user){setMessage('Connecte-toi pour utiliser ton mandat.');return}const [{data:i},{data:st},{data:w}]=await Promise.all([s.from('vl_investor_profiles').select('sectors,stages,geographies,min_ticket_eur,max_ticket_eur,thesis').eq('owner_id',u.user.id).maybeSingle(),s.from('vl_startups').select('id,owner_id,name,sector,stage,description,country,funding_need_eur,verified').eq('status','published'),s.from('vl_watchlist').select('startup_id').eq('investor_id',u.user.id)]);if(!i){setMessage('Configure d’abord ton mandat investisseur.');return}setInvestor(i as Investor);setStartups((st as Startup[])||[]);setWatch(new Set((w||[]).map(x=>x.startup_id)));setMessage('')}
  useEffect(()=>{load()},[])
  const matches=useMemo(()=>investor?startups.map(s=>computeMatch(s,investor)).sort((a,b)=>b.score-a.score):[],[investor,startups])
  async function toggleWatch(id:string){const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user)return;if(watch.has(id)){await s.from('vl_watchlist').delete().eq('investor_id',u.user.id).eq('startup_id',id)}else{const {error}=await s.from('vl_watchlist').insert({investor_id:u.user.id,startup_id:id});if(error){alert(error.message);return}}load()}
  async function createDeal(startupId:string){const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user)return;const {error}=await s.from('vl_deals').insert({investor_id:u.user.id,startup_id:startupId,stage:'interest',next_action:'Prendre contact avec la startup'});alert(error?error.message:'Opportunité ajoutée à la Deal Room.')}
  async function contact(ownerId:string){const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user)return;const text='Bonjour, votre profil apparaît dans mes résultats de matching VentureLink. Je souhaite échanger sur votre projet.';const {error}=await s.from('vl_direct_messages').insert({sender_id:u.user.id,recipient_id:ownerId,body:text});alert(error?error.message:'Message envoyé au fondateur.')}
  return <Shell><div className="stack"><section className="hero"><h1>Matching explicable</h1><p>Le score classe les startups selon ton mandat déclaré. Il ne constitue pas une recommandation d’investissement et ne remplace pas une due diligence.</p></section>{message&&<section className="card muted">{message}</section>}<section className="stack">{matches.map(m=><article className="card match-card" key={m.startup.id}><div className="match-score">{m.score}<small>/100</small></div><div className="match-content"><div className="split"><div><h2>{m.startup.name}</h2><div className="company-meta"><span className="badge">{m.startup.sector||'Secteur ?'}</span><span className="small muted">{m.startup.stage||'Stade ?'}</span><span className="small muted">{m.startup.country||'Pays ?'}</span></div></div><div className="actions"><button className="btn soft" onClick={()=>toggleWatch(m.startup.id)}>{watch.has(m.startup.id)?'Retirer de la watchlist':'Ajouter à la watchlist'}</button><button className="btn ghost" onClick={()=>createDeal(m.startup.id)}>Créer un deal</button><button className="btn primary" onClick={()=>contact(m.startup.owner_id)}>Contacter</button></div></div><p>{m.startup.description||'Description à compléter.'}</p><div className="progress"><span style={{width:`${m.score}%`}}/></div><div className="reason-grid"><div><b>Points compatibles</b><div className="chips static">{m.reasons.map(r=><span className="chip selected" key={r}>{r}</span>)}</div></div><div><b>Points à vérifier</b><div className="chips static">{m.gaps.map(r=><span className="chip warning" key={r}>{r}</span>)}</div></div></div></div></article>)}{!message&&matches.length===0&&<div className="card muted">Aucune startup publique ne peut encore être comparée à ton mandat.</div>}</section></div></Shell>
}
