'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import Shell from '@/components/Shell'
import { createClient } from '@/lib/supabase'

type Post={id:string;body:string;kind:string;created_at:string;author_id:string;startup_id:string|null}
type Profile={id:string;display_name:string}
type Startup={id:string;name:string}
type Like={post_id:string;user_id:string}
type Comment={id:string;post_id:string;author_id:string;body:string;created_at:string}
export default function Feed(){
  const [posts,setPosts]=useState<Post[]>([]);const [profiles,setProfiles]=useState<Profile[]>([]);const [startups,setStartups]=useState<Startup[]>([]);const [likes,setLikes]=useState<Like[]>([]);const [comments,setComments]=useState<Comment[]>([]);const [body,setBody]=useState('');const [kind,setKind]=useState('update');const [msg,setMsg]=useState('');const [me,setMe]=useState('');const [commentDraft,setCommentDraft]=useState<Record<string,string>>({})
  async function load(){const s=createClient();const {data:u}=await s.auth.getUser();setMe(u.user?.id||'');const [{data:p},{data:pr},{data:st},{data:l},{data:c}]=await Promise.all([s.from('vl_posts').select('id,body,kind,created_at,author_id,startup_id').order('created_at',{ascending:false}).limit(50),s.from('vl_profiles').select('id,display_name'),s.from('vl_startups').select('id,name'),s.from('vl_post_likes').select('post_id,user_id'),s.from('vl_comments').select('id,post_id,author_id,body,created_at').order('created_at',{ascending:true})]);setPosts((p as Post[])||[]);setProfiles((pr as Profile[])||[]);setStartups((st as Startup[])||[]);setLikes((l as Like[])||[]);setComments((c as Comment[])||[])}
  useEffect(()=>{load()},[])
  const profileMap=useMemo(()=>Object.fromEntries(profiles.map(p=>[p.id,p.display_name])),[profiles]);const startupMap=useMemo(()=>Object.fromEntries(startups.map(s=>[s.id,s.name])),[startups])
  async function publish(e:FormEvent){e.preventDefault();const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user){setMsg('Connecte-toi pour publier.');return}const {data:owned}=await s.from('vl_startups').select('id').eq('owner_id',u.user.id).maybeSingle();const {error}=await s.from('vl_posts').insert({author_id:u.user.id,startup_id:owned?.id||null,body,kind});if(error){setMsg(error.message);return}setBody('');setMsg('Publication enregistrée.');load()}
  async function toggleLike(postId:string){if(!me){alert('Connecte-toi.');return}const s=createClient();const liked=likes.some(l=>l.post_id===postId&&l.user_id===me);if(liked)await s.from('vl_post_likes').delete().eq('post_id',postId).eq('user_id',me);else await s.from('vl_post_likes').insert({post_id:postId,user_id:me});load()}
  async function addComment(postId:string){const text=(commentDraft[postId]||'').trim();if(!me||!text)return;const {error}=await createClient().from('vl_comments').insert({post_id:postId,author_id:me,body:text});if(error){alert(error.message);return}setCommentDraft({...commentDraft,[postId]:''});load()}
  return <Shell><div className="stack"><section className="hero"><h1>Le réseau où la traction devient visible.</h1><p>Publie des avancées réelles, suis les entreprises qui progressent et transforme les signaux du réseau en opportunités d’investissement.</p></section><section className="card"><form className="stack" onSubmit={publish}><div className="field"><label>Partager une actualité</label><textarea value={body} onChange={e=>setBody(e.target.value)} required placeholder="Nouveau client, pilote, recrutement, certification, résultat produit…"/></div><div className="split"><div className="field compact"><label>Type</label><select value={kind} onChange={e=>setKind(e.target.value)}><option value="update">Actualité</option><option value="milestone">Jalon</option><option value="fundraising">Levée</option><option value="product">Produit</option><option value="hiring">Recrutement</option></select></div><div className="actions"><button className="btn primary">Publier</button>{msg&&<span className="small muted">{msg}</span>}</div></div></form></section><section className="stack">{posts.length===0?<div className="card muted">Aucune publication réelle pour le moment.</div>:posts.map(p=>{const postComments=comments.filter(c=>c.post_id===p.id);const postLikes=likes.filter(l=>l.post_id===p.id);const liked=postLikes.some(l=>l.user_id===me);return <article key={p.id} className="card"><div className="post-head"><div><b>{p.startup_id?startupMap[p.startup_id]:profileMap[p.author_id]||'Membre VentureLink'}</b><div className="small muted">{new Date(p.created_at).toLocaleString('fr-FR')}</div></div><span className="badge">{p.kind}</span></div><div className="post-body">{p.body}</div><div className="post-actions"><button className={`btn ${liked?'soft':'ghost'}`} onClick={()=>toggleLike(p.id)}>♥ {postLikes.length}</button><span className="small muted">{postComments.length} commentaire(s)</span></div>{postComments.length>0&&<div className="comments">{postComments.map(c=><div className="comment" key={c.id}><b>{profileMap[c.author_id]||'Membre'}</b><span>{c.body}</span></div>)}</div>}<div className="comment-compose"><input value={commentDraft[p.id]||''} onChange={e=>setCommentDraft({...commentDraft,[p.id]:e.target.value})} placeholder="Ajouter un commentaire…"/><button className="btn soft" onClick={()=>addComment(p.id)}>Commenter</button></div></article>})}</section></div></Shell>
}
