'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import Shell from '@/components/Shell'
import { createClient } from '@/lib/supabase'

type Project={id:string;title:string;description:string;category:string|null;amount_needed_eur:number;amount_committed_eur:number;help_types:string[];vl_startups?:{name:string}|null}
export default function Boost(){const [projects,setProjects]=useState<Project[]>([]);async function load(){const {data}=await createClient().from('vl_small_projects').select('id,title,description,category,amount_needed_eur,amount_committed_eur,help_types,vl_startups(name)').eq('status','open').order('created_at',{ascending:false});setProjects((data as unknown as Project[])||[])}useEffect(()=>{load()},[]);async function interest(id:string,type:'funding'|'mentoring'|'introduction'){const s=createClient();const {data}=await s.auth.getUser();if(!data.user){alert('Connecte-toi d’abord.');return}const amount=type==='funding'?Number(prompt('Montant envisagé en euros (facultatif)')||0)||null:null;const {error}=await s.from('vl_project_interests').insert({project_id:id,investor_id:data.user.id,help_type:type,amount_eur:amount});alert(error?error.message:'Ton intérêt a été transmis.')}
return <Shell><div className="stack"><section className="hero"><div className="split"><div><h1>Venture Boost</h1><p>Des petits projets concrets peuvent recevoir un financement ciblé, du mentorat ou une mise en relation.</p></div><Link href="/boost/new" className="btn light">Publier un petit projet</Link></div></section><section className="grid">{projects.map(p=>{const pct=Math.min(100,Math.round((p.amount_committed_eur/p.amount_needed_eur)*100));return <article key={p.id} className="card stack"><div><span className="badge">{p.category||'Petit projet'}</span><h2>{p.title}</h2><div className="small muted">{p.vl_startups?.name||'Entreprise'}</div></div><p>{p.description}</p><div><b>{new Intl.NumberFormat('fr-FR').format(p.amount_committed_eur)} €</b> / {new Intl.NumberFormat('fr-FR').format(p.amount_needed_eur)} €<div className="boost-progress"><span style={{width:`${pct}%`}}/></div></div><div className="actions"><button className="btn primary" onClick={()=>interest(p.id,'funding')}>Financer</button><button className="btn soft" onClick={()=>interest(p.id,'mentoring')}>Aider</button><button className="btn ghost" onClick={()=>interest(p.id,'introduction')}>Mettre en relation</button></div></article>})}{projects.length===0&&<div className="card muted">Aucun petit projet public pour le moment.</div>}</section></div></Shell>}
