'use client'
import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import Shell from '@/components/Shell'
import { createClient } from '@/lib/supabase'

type Deal={id:string;investor_id:string;startup_id:string;stage:string;amount_eur:number|null;next_action:string|null;notes:string|null;updated_at:string}
type Startup={id:string;name:string}
const stages=['interest','meeting','due_diligence','offer','closing','closed','declined']
const labels:Record<string,string>={interest:'Intérêt',meeting:'Réunion',due_diligence:'Due diligence',offer:'Offre',closing:'Closing',closed:'Clôturé',declined:'Abandonné'}
export default function Deals(){const [deals,setDeals]=useState<Deal[]>([]);const [startups,setStartups]=useState<Startup[]>([]);const [me,setMe]=useState('');const [role,setRole]=useState('');async function load(){const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user)return;setMe(u.user.id);const [{data:d},{data:st},{data:p}]=await Promise.all([s.from('vl_deals').select('*').order('updated_at',{ascending:false}),s.from('vl_startups').select('id,name'),s.from('vl_profiles').select('role').eq('id',u.user.id).maybeSingle()]);setDeals((d as Deal[])||[]);setStartups((st as Startup[])||[]);setRole(p?.role||'')}useEffect(()=>{load()},[]);const startupMap=useMemo(()=>Object.fromEntries(startups.map(s=>[s.id,s.name])),[startups]);async function updateDeal(id:string,patch:Partial<Deal>){const {error}=await createClient().from('vl_deals').update(patch).eq('id',id);if(error){alert(error.message);return}load()}return <Shell><div className="stack"><section className="hero"><h1>Deal Room</h1><p>Un pipeline privé pour suivre les opportunités depuis l’intérêt initial jusqu’au closing. Les startups concernées peuvent voir le deal ; l’investisseur pilote actuellement l’avancement.</p></section><section className="deal-board">{stages.map(stage=><div className="deal-column" key={stage}><div className="deal-title">{labels[stage]} <span>{deals.filter(d=>d.stage===stage).length}</span></div>{deals.filter(d=>d.stage===stage).map(d=><article className="deal-card" key={d.id}><b>{startupMap[d.startup_id]||'Startup'}</b><small>{d.amount_eur?`${new Intl.NumberFormat('fr-FR').format(d.amount_eur)} €`:'Montant à définir'}</small><Link className="deal-link" href="/data-room">Ouvrir la Data Room</Link>{role==='investor'&&d.investor_id===me?<><select value={d.stage} onChange={e=>updateDeal(d.id,{stage:e.target.value})}>{stages.map(x=><option key={x} value={x}>{labels[x]}</option>)}</select><input defaultValue={d.next_action||''} placeholder="Prochaine action" onBlur={e=>updateDeal(d.id,{next_action:e.target.value})}/></>:<div className="small muted">{d.next_action||'Aucune prochaine action renseignée'}</div>}</article>)}</div>)}</section>{deals.length===0&&<div className="card muted">Aucun deal actif. Depuis le matching, un investisseur peut créer un suivi d’opportunité.</div>}</div></Shell>}
