'use client'
import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import Shell from '@/components/Shell'
import { createClient } from '@/lib/supabase'

const sectors=['IA','ClimateTech','HealthTech','Industry','FinTech','DeepTech','SaaS']
const stages=['Pre-seed','Seed','Series A','Growth']
function toggle(list:string[],value:string){return list.includes(value)?list.filter(x=>x!==value):[...list,value]}
export default function InvestorPage(){
  const [firm,setFirm]=useState('');const [type,setType]=useState('Business Angel');const [thesis,setThesis]=useState('');const [min,setMin]=useState('');const [max,setMax]=useState('');const [selectedSectors,setSelectedSectors]=useState<string[]>([]);const [selectedStages,setSelectedStages]=useState<string[]>([]);const [geographies,setGeographies]=useState('Maroc, France');const [message,setMessage]=useState('');const [ready,setReady]=useState(false);const router=useRouter()
  useEffect(()=>{(async()=>{const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user){router.push('/login');return}const {data:p}=await s.from('vl_profiles').select('role').eq('id',u.user.id).maybeSingle();if(!p){router.push('/onboarding');return}if(p.role!=='investor'){setMessage('Cette page est réservée aux profils investisseurs.');setReady(true);return}const {data:i}=await s.from('vl_investor_profiles').select('*').eq('owner_id',u.user.id).maybeSingle();if(i){setFirm(i.firm||'');setType(i.investor_type||'Business Angel');setThesis(i.thesis||'');setMin(i.min_ticket_eur?String(i.min_ticket_eur):'');setMax(i.max_ticket_eur?String(i.max_ticket_eur):'');setSelectedSectors(i.sectors||[]);setSelectedStages(i.stages||[]);setGeographies((i.geographies||[]).join(', '))}setReady(true)})()},[router])
  async function save(e:FormEvent){e.preventDefault();setMessage('');const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user)return;const payload={owner_id:u.user.id,firm,investor_type:type,thesis,min_ticket_eur:min?Number(min):null,max_ticket_eur:max?Number(max):null,sectors:selectedSectors,stages:selectedStages,geographies:geographies.split(',').map(x=>x.trim()).filter(Boolean)};const {error}=await s.from('vl_investor_profiles').upsert(payload,{onConflict:'owner_id'});setMessage(error?error.message:'Mandat enregistré. Le matching utilise maintenant ces critères.')}
  if(!ready)return <Shell><div className="card">Chargement…</div></Shell>
  return <Shell><div className="stack"><section className="hero"><h1>Mandat d’investissement</h1><p>Définis les critères qui servent au sourcing et au score de compatibilité. Le score reste explicable : chaque point provient d’un critère déclaré.</p></section><section className="card"><form className="stack" onSubmit={save}><div className="form-grid"><div className="field"><label>Structure / fonds</label><input value={firm} onChange={e=>setFirm(e.target.value)} placeholder="Nom du fonds ou investisseur individuel"/></div><div className="field"><label>Type d’investisseur</label><select value={type} onChange={e=>setType(e.target.value)}><option>Business Angel</option><option>VC</option><option>Corporate VC</option><option>Family Office</option><option>Impact Investor</option></select></div></div><div className="form-grid"><div className="field"><label>Ticket minimum (€)</label><input type="number" min="0" value={min} onChange={e=>setMin(e.target.value)}/></div><div className="field"><label>Ticket maximum (€)</label><input type="number" min="0" value={max} onChange={e=>setMax(e.target.value)}/></div></div><div className="field"><label>Secteurs</label><div className="chips">{sectors.map(x=><button type="button" key={x} className={`chip ${selectedSectors.includes(x)?'selected':''}`} onClick={()=>setSelectedSectors(toggle(selectedSectors,x))}>{x}</button>)}</div></div><div className="field"><label>Stades</label><div className="chips">{stages.map(x=><button type="button" key={x} className={`chip ${selectedStages.includes(x)?'selected':''}`} onClick={()=>setSelectedStages(toggle(selectedStages,x))}>{x}</button>)}</div></div><div className="field"><label>Géographies</label><input value={geographies} onChange={e=>setGeographies(e.target.value)} placeholder="Maroc, France, Espagne"/></div><div className="field"><label>Thèse d’investissement</label><textarea value={thesis} onChange={e=>setThesis(e.target.value)} placeholder="Ex. Solutions B2B industrielles avec traction commerciale, équipe technique forte et potentiel de déploiement régional."/></div>{message&&<div className={message.startsWith('Mandat')?'success':'error'}>{message}</div>}<div className="actions"><button className="btn primary">Enregistrer le mandat</button><button className="btn soft" type="button" onClick={()=>router.push('/matching')}>Calculer les matchs</button></div></form></section></div></Shell>
}
